# Generated by Django 3.0.6 on 2020-05-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-created_at"]},
        ),
    ]
