# Generated by Django 3.0.6 on 2020-05-30 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_auto_20200530_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="vote",
            field=models.ManyToManyField(
                blank=True, related_name="vote", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.Post",
            ),
        ),
    ]
