# Generated by Django 3.0.6 on 2020-06-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200530_1602"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="vote", new_name="votes",),
    ]
